[package]
name = "search_enginge"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.4.0"
rayon = "1.11.0"
reqwest = "0.12.24"
scraper = "0.24.0"
serde = "1.0.228"
serde_json = "1.0.145"
tantivy = "0.25.0"
tokio = { version = "1.48.0", features = ["full"] }
url = "2.5.7"
